is_autobid option
daroczig/fbRads pull request #43
Opened 2017-02-06 02:58 UTC by 13bzhang

Hi! Sorry it's been a while since my last pull request to add the `is_autobid` option. I made the code less verbose this time. I tested it today and it works.

2017-02-06 10:34 UTC, daroczig requested changes
Thanks a lot for this! I'd be happy to merge after the above small suggestion, then I can run roxygenize etc, don't worry about that part.

2017-02-06 10:34 UTC, daroczig commented on R/fb_adset.R
> +                              is_autobid, bid_amount,
I think we should set `is_autobid` to `FALSE` by default, as if there's no default value, then L66 below will fail.

2017-02-07 18:20 UTC, 13bzhang commented on R/fb_adset.R
> +                              is_autobid, bid_amount,
OK. I will change that.

2017-02-08 04:48 UTC, 13bzhang commented on R/fb_adset.R
> +                              is_autobid, bid_amount,
Also I need to add `is_autobid` to the documentation.

2017-02-08 04:51 UTC, 13bzhang commented
@daroczig Hi, I made the changes just now.

2017-02-08 18:38 UTC, daroczig approved these changes

2017-02-08 18:38 UTC, merged

2017-02-08 18:40 UTC, daroczig commented
Thanks a lot! Run `roxygen` at https://github.com/cardcorp/fbRads/commit/6d4b0ea75ffc5d3946778b8767ba55bb26933d78